version: '3'

services:
  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - ${SELENIUM_PORT}:4444 # selenium sever port
      - 7900:7900 # 実行中のChromeを確認するVNC用port
  scraping:
    build:
      context: ./scraping
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${SCRAPING_PORT}:8000
    env_file:
      - .env
  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    tty: true
    ports:
      - ${BACKEND_PORT}:8001
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16
    tty: true
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_volume_main:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres_volume_main:
