version: '3'

services:

  scraping:
    build:
      context: ./scraping
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${SCRAPING_PORT}:8000
    env_file:
      - .env
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - ${BACKEND_PORT}:8001
    env_file:
      - .env
  db:
    image: postgres:16
    tty: true
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    env_file:
      - .env
volumes:
  postgres_volume:
