version: '3'

services:
  scraping:
    build: ./scraping
    tty: true
  backend:
    build: ./backend
    tty: true
  db:
    image: postgres:16
    tty: true
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kakeru
      - POSTGRES_PASSWORD=bol
volumes:
  postgres_volume:
